- source/falaise/resource.cc.in
```g++``` version 7.X compiler complains that case instructions can continue to the next one. Fixed by adding break commands.
> Break case statements

- documentation/flsimulate/FLSimulateOutput.md
- source/flsimulate/flsimulatemain.cc
Addresses issue identified in #35, where an "EH" event header bank is required to do cuts based selection of event numbers.
It simply adds the bank to each event in flsimulate for propagation downstream to flvisualize and flreconstruct.
> Add event header bank in flsimulate output

- companions/fecom/src/libs/libfecom/fecom/data_statistics.hpp
GCC 4.9 emits missing-field-initializers warnings, and hence errors, for Fecom's default member initialization of std::array s. This appears to be a bug/oversight in GCC 4.9:
https://stackoverflow.com/questions/31271975/why-can-i-initialize-a-regular-array-from-but-not-a-stdarray
As only default initialization of the arrays is required, remove member initializer.
The test for resolution is passing build on Travis's CentOS6 setup.
> Remove std::array default member initialization

- .travis.yml
Update to Falaise 3.1 introduced new containers. Running on Travis
showed a testing error in tests for FECOM.
To clarify origin of this error, explicitly use older 3.0 version
of containers. If builds pass, it shows that the newer system/brewed
packages in the container are responsible.
This PR is not intended for merging - it is just to trigger a Travis build using the old container explicitly.
> Use 3.0 containers for test

- companions/fecom/src/libs/libfecom/CMakeLists.txt
Updates to CMake on linux highlighted a linking order error in
fecom. Linking Boost libraries prior to libBayeux/libFalaise caused
a runtime error relating to missing serialization registration code
in serialization tests.
Simplify linking of libfecom so that it always links to Bayeux/Falaise
directly and picks up its Boost dependence from them.
> Correct linking order for libfecom

- .github/PULL_REQUEST_TEMPLATE.md
- CONTRIBUTING.md
Document use of GitHub keywords to cross reference and automatically close Issues from PRs that address them. Provide draft Pull Request template. Document how to checkout and review a Pull Request locally.
Fixes #41
> Provide and document Pull Request Template

- modules/EventBrowser/source/browser_tracks.cc
- modules/EventBrowser/source/display_2d.cc
- modules/EventBrowser/source/display_3d.cc
- modules/EventBrowser/source/display_options.cc
- modules/EventBrowser/source/event_browser.cc
- modules/EventBrowser/source/event_selection.cc
- modules/EventBrowser/source/inc/falaise/snemo/view/event_browser_linkdef.h
- modules/EventBrowser/source/progress_bar.cc
- modules/EventBrowser/source/status_bar.cc
Please fill in the following details as appropriate for your pull request.
You can leave any entries that aren't relevant blank.
- Make `clang-format` ignore ROOT pragmas
- Use a semicolon after `ClassImp` to help `clang-format` understand it
- Fixes #64 
Use of semicolon *might* cause compiler warnings.
> Clang format fixes

- modules/EventBrowser/source/CMakeLists.txt
Latest versions of ROOT require additional include paths to be set before
calling root_generate_dictionary.
Please fill in the following details as appropriate for your pull request.
You can leave any entries that aren't relevant blank. If you think the pull request
will need further commits before being ready for review/merge, prepend "WIP:" to
the title.
- Update include_directories to point ROOT to our dictionary headers
- Fixes #.
Needed to support macOS High Sierra, which requires use of ROOT 6.12
> Update inc paths for ROOT 6.12

- modules/GammaClustering/source/falaise/snemo/reconstruction/gamma_clustering_driver.cc
The bug was introduced by this (old) commit https://nemo.lpc-caen.in2p3.fr/changeset/17359 when
removing some pedantic warning of g++.
> fix bug when clustering gammas

- companions/fecom/src/libs/libfecom/fecom/base_hit.cpp
- companions/fecom/src/libs/libfecom/fecom/base_hit.hpp
Please fill in the following details as appropriate for your pull request.
You can leave any entries that aren't relevant blank. If you think the pull request
will need further commits before being ready for review/merge, prepend "WIP:" to
the title.
- single const clarification to `base_hit::compare` call operator
- Fixes #.
AppleClang 9.1 now fails to compile fecom base_hit with a
promoted-to-error warning about base_hit::compare's call
operator not being const.
Make operator explicitly const as it is!
> Make fecom's base_hit comparator call const

- source/falaise/testing/test_property_reader.cxx
- source/flreconstruct/tests/testFhiclProperties.cc
- Fix future gcc 8 warnings but it does not hurt to catch exception by reference as explained here in 2010 https://blog.knatten.org/2010/04/02/always-catch-exceptions-by-reference/
> Always catch exception by reference

- cmake/LPCCMakeSettings.cmake
- Support builds against newer C++ standards
Fix bug that prevented addition of C++14 compile features to list of
overall features.
Add support for compiling against C++17,C++20 when using a CMake version
that knows about these versions.
We'll need this to support coming versions of Boost, ROOT, plus GitDB and Art if we use them.
> Support compilation against C++14,17,20

- modules/ChargedParticleTracking/source/falaise/snemo/reconstruction/calorimeter_association_driver.cc
- modules/GammaClustering/source/falaise/snemo/reconstruction/gamma_clustering_driver.cc
- modules/GammaClustering/testing/test_gamma_clustering_driver.cxx
- source/falaise/snemo/processing/base_tracker_clusterizer.cc
- source/falaise/testing/test_falaise.cxx
- source/falaise/testing/test_falaise_tags.cxx
- source/falaise/testing/test_io_data.cxx
- source/flreconstruct/flreconstructmain.cc
- source/flsimulate/flsimulatecfgmain.cc
- source/flsimulate/flsimulatemain.cc
Please fill in the following details as appropriate for your pull request.
You can leave any entries that aren't relevant blank. If you think the pull request
will need further commits before being ready for review/merge, prepend "WIP:" to
the title.
- Replace use of obsolete Boost interfaces by `std::` equivalents
- Always pass valid args, argv  to `falaise::initialise` because `boost::program_options` requires non-null pointer.
- Fixes #.
Needed irrespective of requested upstream fixes in Bayeux: bxcppdev/Bayeux#36
> Fix interfaces for Boost 1.68

- source/falaise/snemo/cuts/calibrated_data_cut.cc
- source/falaise/snemo/cuts/tracker_trajectory_data_cut.cc
- source/falaise/snemo/processing/base_gamma_builder.cc
- source/falaise/snemo/processing/base_tracker_clusterizer.cc
- source/falaise/snemo/processing/calorimeter_regime.cc
- source/falaise/snemo/processing/geiger_regime.cc
- source/falaise/snemo/processing/mock_calorimeter_s2c_module.cc
- source/falaise/snemo/processing/mock_tracker_s2c_module.cc
- source/falaise/snemo/simulation/cosmic_muon_generator.cc
- source/falaise/snemo/simulation/gg_step_hit_processor.cc
Changes proposed in this pull request:
- If users want to override default values for parameter, they must provide a correct
dimension otherwise the program throws an error and then do not assume anymore a default dimension
value. This avoid misleading initialization of module by assuming wrong default parameter units.
- Fixes #80 .
1) Even if this compiles and seems to work, this fix needs to wait for this PR https://github.com/BxCppDev/Bayeux/pull/15 to work properly.
2) If this looks ok, then one will have to propagate such good habits to all external modules.
> Remove default units for parameters with dimension

- source/falaise/config/property_set.h
- source/falaise/config/quantity.h
- source/falaise/test/test_property_set.cxx
Identified through work on modernizing Falaise. Put/Get of dimensioned
quantities used direct value from "fetch_real_with_explicit_dimension"
member function. This returns the value on the CLHEP scale, e.g.
- 1.2 cm returns a value of "1.2*CLHEP::cm" and a unit symbol of "cm"
This resulted in the conversions performing an additional multiplication
by the scaling factor, resulting in incorrect values.
Update put/get implementations for quantities to divide input values
by the correct unit factor, and multiply output values by it. Add
tests to explicitly check these conversions.
Needed by #149, and should also be applied in a patch release of Falaise 4
> Correct unit conversions in property_set

- programs/flvisualize/EventBrowser/status_bar.cc
- programs/flvisualize/EventBrowser/view/status_bar.h
i have deleted the event combo box. when opening a large data file, the generation of all entries in the combo box and browsing through it is slowing down the GUI. Goto event functionnalities is kept. I added the total number of event in read only mode.
status bar **before** :
status bar **after** :
> flvisualize update : event combo box removed

- source/falaise/test/test_property_set.cxx
Fix compile errors left by leaving version control tags in after merge. Prefer HEAD sections as these are latest on develop branch.
> Remove version control tags left by merge

- .travis/ciscript.sh
- programs/flvisualize/EventBrowser/CMakeLists.txt
Transient dependencies may not otherwise be found. Add an install test to Travis to check running and RPATH post-install.
Fixes #166
> Set install RPATH of EventBrowser plugin to link path

- source/falaise/path.h
- source/falaise/property_set.h
- source/falaise/quantity.h
- source/falaise/snemo/processing/module.h
- source/falaise/snemo/services/service_handle.h
Several classes in Falaise implement custom exceptions for their specific failure cases. These exceptions generally inherit from the standard C++ exceptions declared/defined in the `<stdexcept>` header, but the code included the lower level <exception> header. Lack of compiler errors is likely due to transitive inclusion of `<stdexcept>` by other standard headers in more modern compilers.
Include appropriate `<stdexcept>` header directly to ensure correct classes are declared without incorrectly relying on transitive inclusion.
> Include <stdexcept> for custom exceptions

- CONTRIBUTING.md
- README.md
- documentation/development/CodingStandards.md
Feedback from Bordeaux analysis workshop indicated that additional documentation and walkthroughs of using Git/Hub and Pull Requests is wanted. This begins that process by expanding the main Contribution guide document with a more detailed step-by-step and additional links to documentation.
It's adapted from the ATLAS and Geant4 guides, which have been successful and have the same workflow as Falaise, albeit on CERN's Git infrastructure. Where needed, I've linked out to GitHub's own documentation so that we don't reinvent the wheel or fall behind GitHub's latest and greatest guides.
A few sections remain to be done on review and testing, hence the WIP. I've added quite a few reviewers as this is a broad brush topic, so the more eyes the better!
> Modernize and expand Contribution Guide

- documentation/falaise_doxygen.conf.in
- source/falaise/CMakeLists.txt
- source/falaise/test/test_falaise_version.cxx
- source/falaise/version.cc
- source/falaise/version.cc.in
- source/falaise/version.h.in
This is a very simple PR that helps to speed up incremental and general builds, with no code changes and minimal reorganisation.
Headers are no longer copied to the build area as this was found to lead to significant recompilation. That functionality was originally implemented to help Doxygen generation, but this is no longer needed with the standardised header layout. Doxygen generation and header installs are updated to reflect these changes. There's no change to build/install behaviour.
Falaise's `version.h` file stores two preprocessor symbols for the Git hash and state (if the build is from a Git checkout), plus C++ class functions to get these at runtime. Because the hash/state frequently changes in development (and hence the interface of `version.h`, I was seeing significant …
> Reduce recompilation from copying headers and use of git hash in version.h
